### ISSUE TITLE
GUI backend to control caex

### ISSUE THREAD

**Issue by Ranzer1255** [Ranzer1255/caexbot#45]
GUI for log output and basic control and messaging

**Comment by Ranzer1255** [comment]
would like this to be a separate program from Caex that way it doesn't have to be running while Caex is up. it should be able to connect with caex (if up) and make changes, or start Caex if its not running. also Stop if it is running (that way i dont have to rely on `!sleep` to kill the app

**Comment by ghost** [comment]
Have you, looked at other bots such as mee6 and see if you can ask the owner or devs of the bot how they made the dashboard.

**Comment by Ranzer1255** [comment]
@Lorfdail had mentioned trying a JavaScript based dashboard with node.js I just haven't looked into it yet
